# Generated by Django 6.0.2 on 2026-02-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
