# Generated by Django 6.0.1 on 2026-02-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeeker', '0003_alter_jobseekerprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
