# Generated by Django 6.0.2 on 2026-02-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
