# Generated by Django 6.0.2 on 2026-02-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_companyprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='required_experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
