# Generated by Django 6.0.2 on 2026-02-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_alter_jobposting_required_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='skills_required',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
