# Generated by Django 6.0.2 on 2026-02-16 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_alter_jobposting_skills_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
