# Generated by Django 6.0.1 on 2026-02-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_alter_jobposting_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
