name: CI/CD Pipeline

on:
  push:
  branches:
    - dev
    - main

jobs:
  merge-dev-to-test:
  if: github.ref == 'refs/heads/dev'
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup git
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

    - name: Merge dev into test
      run: |
        git fetch origin
        git checkout test
        git merge dev
        git push origin test